version: '3.3'

services:
  qdrant:
    image: qdrant/qdrant
    ports:
     - "6333:6333"
    volumes:
      - ./data/qdrant_storage:/qdrant/storage
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - qdrant
    ports:
     - "8000:8000"
     - "8080:8080"

networks:
  default:
    driver: bridge

