name: CICD
on: [push]

env:
  JWT_TOKEN: ${{ secrets.JWT_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: "Setup python"
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - run: pip install poetry
      - run: make setup
      - run: make lint
      - run: make test
